[versions]
adjustAndroid = "5.4.5"
adjustAndroidHuaweiReferrer = "5.0.0"
agp = "8.7.0"
billing = "8.2.1"
billingKtx = "8.2.1"
facebookCore = "18.1.3"
# Firebase services versions refers to firebase-bom "33.6", but we use individual versions
# due to issue with publishing to maven
firebaseAnalytics = "22.4.0"
firebaseBom = "34.6.0"
firebaseCrashlytics = "19.4.2"
firebaseCrashlyticsNdk = "19.4.2"
firebaseMessaging = "24.1.1"

gson = "2.10.1"
installreferrer = "2.2"
kotlin = "2.1.21"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxCoroutinesCore = "1.7.3"
#Uncomment for development
#nativeLocal = "0.11.0"
mockitoInline = "5.2.0"
mockitoKotlin = "6.2.3"
noctua-internal-native = "0.13.0"
koinCore = "4.0.0"
robolectric = "4.14.1"
okhttp = "4.12.0"
playServicesAdsIdentifier = "18.1.0"
playServicesAppset = "16.1.0"
lifecycleRuntimeKtx = "2.8.6"
activityCompose = "1.9.2"
composeBom = "2024.09.03"

[libraries]
adjust-android-huawei-referrer = { module = "com.adjust.sdk:adjust-android-huawei-referrer", version.ref = "adjustAndroidHuaweiReferrer" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
adjust-android = { module = "com.adjust.sdk:adjust-android", version.ref = "adjustAndroid" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
facebook-core = { module = "com.facebook.android:facebook-core", version.ref = "facebookCore" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk", version.ref = "firebaseCrashlyticsNdk" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
#Uncomment fo development
#native-local = { module = "com.noctuagames.labs.sdk:native-local", version.ref = "nativeLocal" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
noctua-internal-native = { module = "com.noctuagames.labs.sdk:native", version.ref = "noctua-internal-native" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
play-services-appset = { module = "com.google.android.gms:play-services-appset", version.ref = "playServicesAppset" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }